/* Swarajya — Other Places Index
   Non-fort historical, sacred, and natural sites with Maratha connections.
   Each place has a full detail page (places/{id}/index.html). */

window.PLACES = [
  {
    id: 'bhimashankar-temple',
    name_en: 'Bhimashankar Temple',
    alternate_names: ['Bhimashankar Jyotirlinga'],
    type: 'temple',
    category: 'Jyotirlinga Temple',
    district: 'Pune (Ambegaon)',
    state: 'Maharashtra',
    coordinates: { lat: 19.0722, lng: 73.5358 },
    altitude_m: 1048,
    difficulty: 'moderate',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'Oct – Feb',
    tagline: 'One of the 12 sacred Jyotirlinga shrines — and the forest where the Bhima river is born.',
    maratha_connection: 'The dense Bhimashankar wildlife sanctuary served as a natural buffer protecting the Pune heartland. Chhatrapati Shivaji Maharaj\'s network included the hill fort adjacent to the temple.',
    path: 'places/bhimashankar-temple/index.html',
    published: true
  },
  {
    id: 'naneghat',
    name_en: 'Naneghat',
    alternate_names: ['Nane Ghat', 'Coin Pass'],
    type: 'pass',
    category: 'Ancient Mountain Pass',
    district: 'Pune (Junnar)',
    state: 'Maharashtra',
    coordinates: { lat: 19.2306, lng: 73.6517 },
    altitude_m: 752,
    difficulty: 'moderate',
    family_friendly: true,
    vehicle_access: false,
    best_season: 'Oct – Feb',
    tagline: 'The ancient coin pass — a 2,000-year-old trade route with Satavahana rock inscriptions where tolls were collected in coins.',
    maratha_connection: 'Naneghat was the primary trade artery connecting the Deccan plateau to the Konkan coast. Control of this pass was central to Maratha economic strategy — Jivdhan and Hadsar forts guarded both ends.',
    path: 'places/naneghat/index.html',
    published: true
  },
  {
    id: 'saptashrungi',
    name_en: 'Saptashrungi',
    alternate_names: ['Saptashrungi Devi', 'Seven Peaks'],
    type: 'pilgrimage',
    category: 'Shakti Peetha',
    district: 'Nashik (Vani)',
    state: 'Maharashtra',
    coordinates: { lat: 20.5494, lng: 74.1083 },
    altitude_m: 1416,
    difficulty: 'moderate',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'Oct – Mar',
    tagline: 'The Goddess of the Seven Peaks — one of the three and a half Shakti Peethas of Maharashtra.',
    maratha_connection: 'Saptashrungi Devi was venerated by the Maratha royal family. Chhatrapati Shivaji Maharaj\'s mother Jijabai was a devoted worshipper. The Marathas built and renovated the temple complex during their expansion into northern Maharashtra.',
    path: 'places/saptashrungi/index.html',
    published: true
  },
  {
    id: 'gharapuri',
    name_en: 'Gharapuri (Elephanta)',
    alternate_names: ['Elephanta Island', 'Agashi'],
    type: 'cave',
    category: 'UNESCO Cave Temples',
    district: 'Mumbai',
    state: 'Maharashtra',
    coordinates: { lat: 18.9633, lng: 72.9315 },
    altitude_m: 10,
    difficulty: 'easy',
    family_friendly: true,
    vehicle_access: false,
    best_season: 'Nov – Feb',
    tagline: 'The island of cave temples — 5th–8th century rock-cut shrines dedicated to Shiva, 10 km from Mumbai.',
    maratha_connection: 'Gharapuri lay at the entrance to Bombay harbour — strategically vital. Kanhoji Angre\'s Maratha navy contested these waters. The island was in the zone of constant Maratha–Portuguese–British rivalry in the Arabian Sea.',
    path: 'places/gharapuri/index.html',
    published: true
  },
  {
    id: 'lenyadri',
    name_en: 'Lenyadri',
    alternate_names: ['Jnanesvari', 'Ganesh Lena'],
    type: 'cave',
    category: 'Buddhist & Ashtavinayak Caves',
    district: 'Pune (Junnar)',
    state: 'Maharashtra',
    coordinates: { lat: 19.2250, lng: 73.8583 },
    altitude_m: 780,
    difficulty: 'moderate',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'Oct – Feb',
    tagline: 'Rock-cut Buddhist caves from the 1st–3rd century CE — and the only Ashtavinayak Ganesh shrine inside a cave.',
    maratha_connection: 'Lenyadri sits in the Junnar region — the heartland surrounding Shivneri fort where Chhatrapati Shivaji Maharaj was born. The Junnar area was one of the first territories consolidated by Swarajya.',
    path: 'places/lenyadri/index.html',
    published: true
  },
  {
    id: 'mangi-tungi',
    name_en: 'Mangi-Tungi',
    alternate_names: ['Managiri-Tungiri'],
    type: 'pilgrimage',
    category: 'Jain Sacred Twin Peaks',
    district: 'Nashik (Satana)',
    state: 'Maharashtra',
    coordinates: { lat: 20.6611, lng: 74.4472 },
    altitude_m: 1309,
    difficulty: 'hard',
    family_friendly: false,
    vehicle_access: false,
    best_season: 'Oct – Feb',
    tagline: 'Two sacred Jain peaks with 108 Jain temples on Mangi and the world\'s tallest Rishabhanatha statue on Tungi.',
    maratha_connection: 'The Mangi-Tungi range sits in the northern Nashik district, the same zone where the Battle of Salher was fought (1672). The Marathas\' respect for Jain pilgrimage sites was part of their policy of religious tolerance.',
    path: 'places/mangi-tungi/index.html',
    published: true
  },
  {
    id: 'panhalekaji',
    name_en: 'Panhalekaji Caves',
    alternate_names: ['Panhalekaji Buddhist Caves'],
    type: 'cave',
    category: 'Buddhist Rock-Cut Caves',
    district: 'Ratnagiri (Sangameshwar)',
    state: 'Maharashtra',
    coordinates: { lat: 17.2583, lng: 73.6236 },
    altitude_m: 220,
    difficulty: 'easy',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'Oct – Mar',
    tagline: '29 rock-cut Buddhist caves from the 2nd–9th century — the only caves of this scale in coastal Konkan.',
    maratha_connection: 'The Konkan coast was a key corridor of Maratha naval power. Sangameshwar taluka, where these caves sit, was in the territory watched over by Maratha coastal forts including Suvarnadurg.',
    path: 'places/panhalekaji/index.html',
    published: true
  },
  {
    id: 'pateshwar',
    name_en: 'Pateshwar',
    alternate_names: ['Pateshwar Caves', 'Patas'],
    type: 'cave',
    category: 'Rock-Cut Shiva Temples',
    district: 'Satara (Khatav)',
    state: 'Maharashtra',
    coordinates: { lat: 17.6667, lng: 74.5333 },
    altitude_m: 640,
    difficulty: 'easy',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'Oct – Mar',
    tagline: 'Remarkable rock-cut Shiva temples in the Satara plateau — with a 9th-century Nandi carved from a single boulder.',
    maratha_connection: 'Pateshwar lies deep in Satara district — the heart of the Maratha homeland. The surrounding territory was integral to Chhatrapati Shivaji Maharaj\'s early campaigns in the 1650s and 1660s.',
    path: 'places/pateshwar/index.html',
    published: true
  },
  {
    id: 'kalsubai',
    name_en: 'Kalsubai Peak',
    alternate_names: ['Roof of Maharashtra'],
    type: 'peak',
    category: 'Sacred Summit',
    district: 'Ahmednagar (Akole)',
    state: 'Maharashtra',
    coordinates: { lat: 19.5956, lng: 73.7134 },
    altitude_m: 1646,
    difficulty: 'moderate',
    family_friendly: false,
    vehicle_access: false,
    best_season: 'Oct – Feb',
    tagline: 'The highest peak in Maharashtra at 1,646 m — with a Kalsubai Devi temple at the summit.',
    maratha_connection: 'Kalsubai stands in the Kalsubai-Harishchandragad wildlife corridor — the same range that sheltered multiple Maratha forts. The summit commands panoramic views of Ratangad, Harishchandragad, and Ajoba.',
    path: 'places/kalsubai/index.html',
    published: true
  },
  {
    id: 'pavan-khind',
    name_en: 'Pavan Khind',
    alternate_names: ['Ghod Khind', 'Pass of the Wind'],
    type: 'battlefield',
    category: 'Historic Battlefield & Pass',
    district: 'Kolhapur',
    state: 'Maharashtra',
    coordinates: { lat: 16.7300, lng: 74.0500 },
    altitude_m: 560,
    difficulty: 'easy',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'Oct – Mar',
    tagline: 'The Pass of the Wind — where Baji Prabhu Deshpande held 10,000 soldiers with 300 men so Chhatrapati Shivaji Maharaj could reach Vishalgad alive.',
    maratha_connection: 'On 13 July 1660, Baji Prabhu Deshpande held this narrow mountain pass against Siddi Masud\'s pursuing army. He fell in battle but the three cannon shots from Vishalgad — signalling Chhatrapati Shivaji Maharaj\'s safe arrival — were the last sounds he heard.',
    path: 'places/pavan-khind/index.html',
    published: true
  },
  {
    id: 'wai-krishna',
    name_en: 'Wai (Krishna river)',
    alternate_names: ['Vireshwar', 'Dakshin Kashi'],
    type: 'historic_site',
    category: 'Sacred Town on the Krishna',
    district: 'Satara (Wai)',
    state: 'Maharashtra',
    coordinates: { lat: 17.9583, lng: 73.8833 },
    altitude_m: 580,
    difficulty: 'easy',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'Oct – Mar',
    tagline: 'The Dakshin Kashi of Maharashtra — ancient temples on the Krishna river bank, with 18 ghats and a living pilgrimage tradition.',
    maratha_connection: 'Wai was an important religious and administrative town in Satara district. It sits directly below Pandavgad fort and was part of the Maratha core territory. Many Maratha nobles patronised the temples here.',
    path: 'places/wai-krishna/index.html',
    published: true
  },
  {
    id: 'trimbakeshwar',
    name_en: 'Trimbakeshwar',
    alternate_names: ['Trimbak', 'Trimbakeshwara Jyotirlinga'],
    type: 'temple',
    category: 'Jyotirlinga Temple',
    district: 'Nashik (Trimbakeshwar)',
    state: 'Maharashtra',
    coordinates: { lat: 19.9308, lng: 73.5292 },
    altitude_m: 778,
    difficulty: 'easy',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'Oct – Mar',
    tagline: 'The Jyotirlinga at the source of the Godavari — one of the 12 sacred Shiva shrines, with the Trimbakgad fort on the hill above.',
    maratha_connection: 'The Maratha Peshwas patronised Trimbakeshwar extensively and funded renovation of the existing temple. The Nashik–Trimbak region was integral to Maratha religious policy. Trimbakgad fort directly above protected the sacred town.',
    path: 'places/trimbakeshwar/index.html',
    published: true
  },
  {
    id: 'dutch-warehouse-vengurla',
    name_en: 'Dutch Warehouse, Vengurla',
    alternate_names: ['VOC Warehouse', 'Dutch Factory'],
    type: 'historic_site',
    category: 'Dutch Colonial Trading Post',
    district: 'Sindhudurg (Vengurla)',
    state: 'Maharashtra',
    coordinates: { lat: 15.8614, lng: 73.6331 },
    altitude_m: 10,
    difficulty: 'easy',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'Oct – Mar',
    tagline: 'A 17th-century Dutch East India Company trading warehouse — one of the best-preserved VOC structures on the Indian coast.',
    maratha_connection: 'Vengurla was a key port in Kanhoji Angre\'s territory. The Dutch factory here operated at the pleasure of the Maratha naval chief. Its survival reflects the pragmatic trade relationships between the Maratha navy and European merchants.',
    path: 'places/dutch-warehouse-vengurla/index.html',
    published: true
  },
  {
    id: 'umberkhind',
    name_en: 'Umberkhind',
    alternate_names: ['Battle of Umberkhind'],
    type: 'battlefield',
    category: 'Historic Battlefield',
    district: 'Raigad (Khalapur)',
    state: 'Maharashtra',
    coordinates: { lat: 18.7833, lng: 73.2667 },
    altitude_m: 380,
    difficulty: 'easy',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'Oct – Mar',
    tagline: 'The jungle ambush that humiliated the Mughal empire — in January 1661, Chhatrapati Shivaji Maharaj defeated Shaista Khan\'s advance force without losing a single man.',
    maratha_connection: 'One of the most tactically brilliant battles of Chhatrapati Shivaji Maharaj\'s career. Using the dense forest terrain, he trapped a large Mughal column in a narrow valley, destroying it completely. A pure demonstration of Ganimi Kava — guerrilla strategy.',
    path: 'places/umberkhind/index.html',
    published: true
  },
  {
    id: 'shivneri-jijabai-memorial',
    name_en: 'Jijabai Memorial, Sindhudurg',
    alternate_names: ['Rajmata Jijabai Smriti Sthal'],
    type: 'historic_site',
    category: 'Memorial Site',
    district: 'Sindhudurg',
    state: 'Maharashtra',
    coordinates: { lat: 16.1500, lng: 73.7500 },
    altitude_m: 15,
    difficulty: 'easy',
    family_friendly: true,
    vehicle_access: true,
    best_season: 'All year',
    tagline: 'Memorial to Rajmata Jijabai — the mother who shaped Chhatrapati Shivaji Maharaj and the conscience of Swarajya.',
    maratha_connection: 'Rajmata Jijabai (1598–1674) is the foundational figure of Swarajya. She raised Chhatrapati Shivaji Maharaj with stories of Ramayana, Mahabharata, and the idea that the people of Maharashtra deserved their own kingdom. She lived to see his coronation and died 12 days later.',
    path: 'places/shivneri-jijabai-memorial/index.html',
    published: true
  }
];
